import requests
import json
import os

class SummarizerAgent:

    def __init__(self, prompt: str, api_key: str, model_name: str = "gemini-2.5-flash-preview-05-20"):
        self.prompt = prompt
        self.api_key = api_key
        self.model_name = model_name

    def summraize(self):
    
        if not self.api_key:
            return "Error: API key is missing. Please provide your Google Cloud API key."

        # Gemini API endpoint for text generation
        api_url = f"https://generativelanguage.googleapis.com/v1beta/models/{self.model_name}:generateContent?key={self.api_key}"

        payload = {
            "contents": [
                {"role": "user", "parts": [{"text": self.prompt}]}
            ],
            "generationConfig": {
                    "maxOutputTokens": 500
            }
        }
        headers = {
            "Content-Type": "application/json"
        }

        print(f"Sending request to Gemini API...")
        response = requests.post(api_url, headers=headers, data=json.dumps(payload))
        response.raise_for_status() # Raise an HTTPError for bad responses (4xx or 5xx)

        # Parse the JSON response
        result = response.json()

        # Extract the generated text
        if result.get("candidates") and len(result["candidates"]) > 0:
            first_candidate = result["candidates"][0]
            if first_candidate.get("content") and first_candidate["content"].get("parts"):
                if len(first_candidate["content"]["parts"]) > 0:
                    return first_candidate["content"]["parts"][0].get("text", "No text part found in response.")
        return "No valid text generated by the model." # Fallback if structure is unexpected
    

class SummarizerEvaluatorAgent:

    def __init__(self, prompt: str, api_key: str, model_name: str = "gemini-2.5-flash-preview-05-20"):
        self.prompt = prompt
        self.api_key = api_key
        self.model_name = model_name

    def evaluate(self):
    
        if not self.api_key:
            return "Error: API key is missing. Please provide your Google Cloud API key."

        # Gemini API endpoint for text generation
        api_url = f"https://generativelanguage.googleapis.com/v1beta/models/{self.model_name}:generateContent?key={self.api_key}"

        payload = {
            "contents": [
                {"role": "user", "parts": [{"text": self.prompt}]}
            ],
            "generationConfig": {
                    "maxOutputTokens": 500
            }
        }
        headers = {
            "Content-Type": "application/json"
        }

        print(f"Sending request to Gemini API...")
        response = requests.post(api_url, headers=headers, data=json.dumps(payload))
        response.raise_for_status() # Raise an HTTPError for bad responses (4xx or 5xx)

        # Parse the JSON response
        result = response.json()

        # Extract the generated text
        if result.get("candidates") and len(result["candidates"]) > 0:
            first_candidate = result["candidates"][0]
            if first_candidate.get("content") and first_candidate["content"].get("parts"):
                if len(first_candidate["content"]["parts"]) > 0:
                    return first_candidate["content"]["parts"][0].get("text", "No text part found in response.")
        return "No valid text generated by the model." # Fallback if structure is unexpected

       


# --- How to use this function ---
if __name__ == "__main__":

    api_key = os.environ["GOOGLE_API_KEY"]
    email_text = """My name is Rohan and I am a Staffing Specialist at NextGen Technologies Inc. I am reaching out to you on an exciting job opportunity with one of our clients. Please have a look at the below job description and share your Resume along with the link to the LINKEDIN PROFILE, if you would like to know more about the role.

   

Role: Prompt Engineer

Location: Houston, Texas

Duration: Long Term Contract

 

Job description:

We are seeking a skilled Prompt Engineer to join our team. As a Prompt Engineer, you will be responsible for developing and optimizing prompt structures for various AI models, ensuring that they perform at their best across different applications. You will work closely with our GenAI Engineers to ensure seamless integration and optimization of AI models.

 

Key Responsibilities

Prompt Design: Develop and optimize prompt structures for multiple AI models (e.g., GPT, GEMINI, etc.), ensuring they are tailored to specific use cases.

Model Understanding: Work with data scientists and engineers to understand the unique requirements of different models and design prompts that maximize their performance.

AI Model Integration: Collaborate with other engineering teams to integrate and test prompts within various AI-driven applications.

Optimization: Continuously analyze and improve the effectiveness of prompts through testing and iterative improvements.

Documentation: Document prompt structures, models, and best practices to ensure scalability and knowledge sharing.

 

Required Skills and Qualifications

Experience: 2+ years of experience in prompt engineering, natural language processing, or related AI fields.

Technical Expertise: Deep understanding of prompting structures for AI models and experience working with large language models (LLMs) like GPT, GEMINI, etc.

Programming: Proficiency in Python and AI-related libraries (TensorFlow, PyTorch, etc.).

AI Tools: Familiarity with AI platforms and tools for model orchestration and testing (e.g., Google ADK, LangChain, etc.).

Cloud Platform: GCP, Azure.

Problem-Solving: Strong problem-solving skills and the ability to develop innovative prompt strategies to optimize model performance.

 

Should you be interested, please send me a copy of your resume along with the LinkedIn link ASAP.

 

 

Thanks & Regards

 

Rohan Dhaliwal

Contact: - (669) 333-3067 |Email – rohan@nextgentechinc.com

NextGen Technologies Inc."""
    user_prompt = f"""You are email sumarizer assistant. You will be provided with an email text and summarize the email in a concise way. Here is the email text: {email_text}"""
    # < context length
    ag = SummarizerAgent(user_prompt, api_key)
    actual_email_summary = ag.summraize()
    print(actual_email_summary)
    ev_prompt = f"""You are summarizer evaluator. You have to provide a similarity confidene score between the expected email summary and actual email summary. Here is the actual email summary:
      {actual_email_summary}
      Here is the expected email summary:
      Rohan Dhaliwal, a Staffing Specialist at NextGen Technologies Inc., is reaching out about a long-term contract opportunity for a **Prompt Engineer** in Houston, Texas. The role involves developing and optimizing prompt structures for various AI models (e.g., GPT, GEMINI). They are seeking candidates with 2+ years of experience in prompt engineering, strong technical expertise in LLMs, proficiency in Python, and familiarity with AI platforms/cloud platforms (GCP, Azure). If interested, please send your resume and LinkedIn profile link
     """
    ev_Ag = SummarizerEvaluatorAgent(ev_prompt, api_key)
    print(ev_Ag.evaluate())

    #while < 