name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 
      - name: Set up Python
        uses: actions/setup-python@v5 
        with:
          python-version: '3.12.5' 

      - name: print message
        run: echo "printing sum of two numbers"

      - name: Run Tests
        run: python3 test.py

  
