name: DataFrame pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  DataFrameShape-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
         python-version: '3.12.5'

      - name: print message
        run: echo "Staring test..."
      - name: Run Tests
        run: python3 data_generator.py
  
